version: '3'

services:

  auth-service:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: auth-service
    ports:
      - "9001:8080"
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
#    network_mode: "host"